on:
  push:
    branch:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '14.15.1'
    - name: Install node packages
      run: yarn --frozen-lockfile
    - name: Build
      run: yarn build

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '14.15.1'
    - name: Install node packages
      run: yarn --frozen-lockfile
    - name: Run tests
      run: yarn test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '14.15.1'
    - name: Install node packages
      run: yarn --frozen-lockfile
    - name: Lint
      run: yarn lint
