on:
  push:
    branch:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up node using nvm
      uses:  dcodeIO/setup-node-nvm@v4
    - name: Install node packages
      run: |
        nvm use `cat .nvmrc`
        npm install --global yarn
        yarn build
    - name: Build
      run: yarn build

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up node using nvm
      uses:  dcodeIO/setup-node-nvm@v4
    - name: Install node packages
      run: |
        nvm use `cat .nvmrc`
        npm install --global yarn
        yarn build
    - name: Run tests
      run: yarn test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up node using nvm
      uses:  dcodeIO/setup-node-nvm@v4
    - name: Install node packages
      run: |
        nvm use `cat .nvmrc`
        npm install --global yarn
        yarn build
    - name: Lint
      run: yarn lint
