on:
  push:
    branch:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '14.15.1'
    - name: Install node packages
      env:
        GITHUB_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cp .npmrc.example .npmrc
        yarn --frozen-lockfile
    - name: Build
      env:
        GITHUB_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: yarn build

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '14.15.1'
    - name: Install node packages
      env:
        GITHUB_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cp .npmrc.example .npmrc
        yarn --frozen-lockfile
    - name: Run tests
      env:
        GITHUB_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: yarn test
    - uses: actions/upload-artifact@v2
      with:
        name: Test Coverage
        path: coverage/lcov-report
        retention-days: 5

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '14.15.1'
    - name: Install node packages
      env:
        GITHUB_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cp .npmrc.example .npmrc
        yarn --frozen-lockfile
    - name: Lint
      env:
        GITHUB_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: yarn lint
